# Service config
server:
  servlet:
    context-path: /service

# Logging configuration.
logging:
  level:
    org:
      springframework: INFO
management:
  security:
    enabled: false

endpoints:
  health:
    id: health
    path: /health
    enabled: true
    sensitive: false
